version: '3.9'
services:
  accounting-manager-db:
    image: postgres:latest
    container_name: accounting-manager-db
    ports:
      - "5432:5432"
    networks:
      - accounting-workspace-network
    volumes:
      - ./accounting-manager/docker/postgres/initDb.sql:/docker-entrypoint-initdb.d/initDb.sql
    environment:
      POSTGRES_DB: accounting-manager-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  service-discovery:
    image: service-discovery:0.0.1-SNAPSHOT
    build:
      context: ./service-discovery
    networks:
      - accounting-workspace-network
    ports:
      - "6969:6969"
    expose:
      - "6969"
    depends_on:
      config-server:
        condition: service_started
    environment:
      SERVER_PORT: 6969
      SERVICE_DISCOVERY_URL: service-discovery
  api-gateway:
    image: api-gateway:0.0.1-SNAPSHOT
    build:
      context: ./api-gateway
    networks:
      - accounting-workspace-network
    ports:
      - "8833:8833"
    expose:
      - "8833"
    depends_on:
      config-server:
        condition: service_started
      service-discovery:
        condition: service_started
    environment:
      SERVER_PORT: 8833
      SERVICE_DISCOVERY_DEFAULT_ZONE: http://service-discovery:6969/eureka
    links:
      - service-discovery:service-discovery
  accounting-manager:
    image: accounting-manager:0.0.1-SNAPSHOT
    build:
      context: ./accounting-manager
    networks:
      - accounting-workspace-network
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      accounting-manager-db:
        condition: service_healthy
      config-server:
        condition: service_started
      service-discovery:
        condition: service_started
      api-gateway:
        condition: service_started
    environment:
      SERVER_PORT: 8081
      SERVICE_DISCOVERY_DEFAULT_ZONE: http://service-discovery:6969/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://accounting-manager-db:5432/accounting-manager-db?currentSchema=accounting-manager
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_HIKARI_SCHEMA: accounting-manager
      SPRING_FLYWAY_URL: jdbc:postgresql://accounting-manager-db:5432/accounting-manager-db
      SPRING_FLYWAY_USER: admin
      SPRING_FLYWAY_PASSWORD: admin
      SPRING_FLYWAY_SCHEMAS: accounting-manager
    links:
      - service-discovery:service-discovery
      - api-gateway:api-gateway
      - accounting-manager-db:accounting-manager-db
networks:
  accounting-workspace-network: