package evrentan.accounting.accountingmanager.entity;

import evrentan.accounting.accountingmanager.dto.entity.Accounting;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Accounting Entity Class represents the community table in the database.
 * It is represented by {@link Accounting} in DTO level.
 *
 * @author <a href="https://github.com/evrentan">Evren Tan</a>
 * @since 1.0.0
 */
@Entity
@Table(name = "accounting")
@Getter @Setter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@EqualsAndHashCode @ToString
@Builder
public class AccountingEntity {

    /**
     * Accounting ID in UUID Type.
     * It is equalized to the id column in the database.
     * It is the primary key of the table.
     * It is auto-generated by the database.
     * It is unique.
     * It is not nullable.
     *
     * @since 1.0.0
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private UUID id;

    /**
     * First Name of the Accountant in String Type.
     * It is equalized to the first_name column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "first_name")
    private String firstName;

    /**
     * Last Name of the Accountant in String Type.
     * It is equalized to the last_name column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "last_name")
    private String lastName;

    /**
     * Email of the Accountant in String Type.
     * It is equalized to the email column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "email")
    private String email;

    /**
     * Amount of the Bill in Double Type.
     * It is equalized to the amount column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "amount")
    private BigDecimal amount;

    /**
     * Product Name in String Type.
     * It is equalized to the product_name column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "product_name")
    private String productName;

    /**
     * Bill No in String Type.
     * It is equalized to the bill_no column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "bill_no")
    private String billNo;

    /**
     * Indicates whether the accounting item is active or not.
     * It is equalized to the is_active column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "is_active")
    private boolean isActive;

    /**
     * Bill Date in LocalDateTime Type.
     * It is equalized to the bill_date column in the database.
     *
     * @since 1.0.0
     */
    @Basic
    @Column(name = "bill_date")
    private LocalDateTime billDate;
}
